Till now we did classification problem. Let's now try looking at one regression problem, utilizing the boston housing dataset. This is the simplest method and I am going to make use of GPU for carrying out the task.

In [2]:
import tensorflow as tf  # Importing tensorflow

print(tf.config.list_physical_devices('GPU'))  #Checking if my jupyter notebook can access my GPU

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
# Since I have the GPU available, I will make use of it with the following code

gpus = tf.config.list_physical_devices('GPU')

if gpus:
    try:
        # Set memory growth to avoid using all GPU memory at once
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU is set up and ready!")
    except RuntimeError as e:
        print(e)

GPU is set up and ready!


In [22]:
import numpy as np  # Importing numpy for numerical operations
from sklearn.preprocessing import StandardScaler # Importing StandardScaler for normalization

In [23]:
boston = tf.keras.datasets.boston_housing  # Loading the boston housing dataset

In [24]:
(train_features, train_label), (test_features, test_label) = boston.load_data()

In [25]:
print('Shape of train set - \n')
print(train_features.shape)
print(train_label.shape)
print('\nShape of test set -\n')
print(test_features.shape)
print(test_label.shape)

Shape of train set - 

(404, 13)
(404,)

Shape of test set -

(102, 13)
(102,)


In [26]:
train_features[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [27]:
train_label[0]

15.2

In [28]:
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [29]:
train_features[0]

array([-0.27224633, -0.48361547, -0.43576161, -0.25683275, -0.1652266 ,
       -0.1764426 ,  0.81306188,  0.1166983 , -0.62624905, -0.59517003,
        1.14850044,  0.44807713,  0.8252202 ])

In [30]:
# Data is ready. Let's start with the model building

model = tf.keras.models.Sequential([
    tf.keras.Input(shape=(13,)),
    tf.keras.layers.Dense(256, activation = 'relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')  #linear is the default form of activation
])

model.compile(optimizer='adam', loss='mse', metrics=['accuracy', 'mae'])

Here we used a linear activation function. This function outputs the input as is, without applying any transformation. It is used in the output layer for regression tasks where the model needs to predict continuous values.
Limitation is that it lacks non-linearity, meaning it cannot model complex patterns when used in hidden layers.

In [31]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 256)               3584      
                                                                 
 dense_7 (Dense)             (None, 128)               32896     
                                                                 
 dense_8 (Dense)             (None, 1)                 129       
                                                                 
Total params: 36,609
Trainable params: 36,609
Non-trainable params: 0
_________________________________________________________________


In [32]:
class mycallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if logs['loss'] < 0.60:
            self.model.stop_training = True
            

In [33]:
model.fit(train_features, train_label, epochs = 500, callbacks=[mycallback()])

Epoch 1/500
13/13 [==============================] - 0s 12ms/step - loss: 501.6205 - accuracy: 0.0000e+00 - mae: 20.4369
Epoch 2/500
13/13 [==============================] - 0s 10ms/step - loss: 303.3810 - accuracy: 0.0000e+00 - mae: 15.0537
Epoch 3/500
13/13 [==============================] - 0s 11ms/step - loss: 108.1524 - accuracy: 0.0000e+00 - mae: 8.1216
Epoch 4/500
13/13 [==============================] - 0s 11ms/step - loss: 58.1916 - accuracy: 0.0000e+00 - mae: 5.7614
Epoch 5/500
13/13 [==============================] - 0s 11ms/step - loss: 33.7977 - accuracy: 0.0000e+00 - mae: 4.2356
Epoch 6/500
13/13 [==============================] - 0s 10ms/step - loss: 24.3529 - accuracy: 0.0000e+00 - mae: 3.4991
Epoch 7/500
13/13 [==============================] - 0s 9ms/step - loss: 20.6864 - accuracy: 0.0000e+00 - mae: 3.2559
Epoch 8/500
13/13 [==============================] - 0s 9ms/step - loss: 18.5281 - accuracy: 0.0000e+00 - mae: 3.0378
Epoch 9/500
13/13 [==========================

13/13 [==============================] - 0s 11ms/step - loss: 6.4748 - accuracy: 0.0000e+00 - mae: 1.7937
Epoch 70/500
13/13 [==============================] - 0s 12ms/step - loss: 6.3778 - accuracy: 0.0000e+00 - mae: 1.8117
Epoch 71/500
13/13 [==============================] - 0s 12ms/step - loss: 6.2060 - accuracy: 0.0000e+00 - mae: 1.7680
Epoch 72/500
13/13 [==============================] - 0s 12ms/step - loss: 6.3460 - accuracy: 0.0000e+00 - mae: 1.7626
Epoch 73/500
13/13 [==============================] - 0s 11ms/step - loss: 6.2414 - accuracy: 0.0000e+00 - mae: 1.8159
Epoch 74/500
13/13 [==============================] - 0s 12ms/step - loss: 6.3704 - accuracy: 0.0000e+00 - mae: 1.7834
Epoch 75/500
13/13 [==============================] - 0s 10ms/step - loss: 6.1073 - accuracy: 0.0000e+00 - mae: 1.7597
Epoch 76/500
13/13 [==============================] - 0s 11ms/step - loss: 6.2135 - accuracy: 0.0000e+00 - mae: 1.7723
Epoch 77/500
13/13 [==============================] - 0s 11ms

13/13 [==============================] - 0s 12ms/step - loss: 4.0887 - accuracy: 0.0000e+00 - mae: 1.4394
Epoch 138/500
13/13 [==============================] - 0s 13ms/step - loss: 4.1696 - accuracy: 0.0000e+00 - mae: 1.4722
Epoch 139/500
13/13 [==============================] - 0s 12ms/step - loss: 4.0626 - accuracy: 0.0000e+00 - mae: 1.4317
Epoch 140/500
13/13 [==============================] - 0s 11ms/step - loss: 4.2528 - accuracy: 0.0000e+00 - mae: 1.4939
Epoch 141/500
13/13 [==============================] - 0s 12ms/step - loss: 4.1024 - accuracy: 0.0000e+00 - mae: 1.4391
Epoch 142/500
13/13 [==============================] - 0s 10ms/step - loss: 3.9522 - accuracy: 0.0000e+00 - mae: 1.3909
Epoch 143/500
13/13 [==============================] - 0s 10ms/step - loss: 3.9196 - accuracy: 0.0000e+00 - mae: 1.3995
Epoch 144/500
13/13 [==============================] - 0s 11ms/step - loss: 4.0422 - accuracy: 0.0000e+00 - mae: 1.4508
Epoch 145/500
13/13 [==============================] -

13/13 [==============================] - 0s 9ms/step - loss: 2.7966 - accuracy: 0.0000e+00 - mae: 1.2125
Epoch 206/500
13/13 [==============================] - 0s 9ms/step - loss: 2.4934 - accuracy: 0.0000e+00 - mae: 1.1106
Epoch 207/500
13/13 [==============================] - 0s 10ms/step - loss: 2.7329 - accuracy: 0.0000e+00 - mae: 1.1838
Epoch 208/500
13/13 [==============================] - 0s 11ms/step - loss: 2.5654 - accuracy: 0.0000e+00 - mae: 1.1583
Epoch 209/500
13/13 [==============================] - 0s 10ms/step - loss: 2.9381 - accuracy: 0.0000e+00 - mae: 1.2820
Epoch 210/500
13/13 [==============================] - 0s 9ms/step - loss: 2.6515 - accuracy: 0.0000e+00 - mae: 1.2062
Epoch 211/500
13/13 [==============================] - 0s 11ms/step - loss: 2.6372 - accuracy: 0.0000e+00 - mae: 1.1742
Epoch 212/500
13/13 [==============================] - 0s 10ms/step - loss: 2.6559 - accuracy: 0.0000e+00 - mae: 1.2016
Epoch 213/500
13/13 [==============================] - 0s

13/13 [==============================] - 0s 10ms/step - loss: 1.7793 - accuracy: 0.0000e+00 - mae: 1.0127
Epoch 274/500
13/13 [==============================] - 0s 13ms/step - loss: 1.7382 - accuracy: 0.0000e+00 - mae: 0.9625
Epoch 275/500
13/13 [==============================] - 0s 12ms/step - loss: 1.6164 - accuracy: 0.0000e+00 - mae: 0.9335
Epoch 276/500
13/13 [==============================] - 0s 11ms/step - loss: 1.6406 - accuracy: 0.0000e+00 - mae: 0.9281
Epoch 277/500
13/13 [==============================] - 0s 12ms/step - loss: 1.5979 - accuracy: 0.0000e+00 - mae: 0.9072
Epoch 278/500
13/13 [==============================] - 0s 13ms/step - loss: 1.6439 - accuracy: 0.0000e+00 - mae: 0.9253
Epoch 279/500
13/13 [==============================] - 0s 10ms/step - loss: 1.7467 - accuracy: 0.0000e+00 - mae: 0.9672
Epoch 280/500
13/13 [==============================] - 0s 11ms/step - loss: 1.8398 - accuracy: 0.0000e+00 - mae: 0.9539
Epoch 281/500
13/13 [==============================] -

13/13 [==============================] - 0s 13ms/step - loss: 1.0747 - accuracy: 0.0000e+00 - mae: 0.7255
Epoch 342/500
13/13 [==============================] - 0s 11ms/step - loss: 1.0807 - accuracy: 0.0000e+00 - mae: 0.7377
Epoch 343/500
13/13 [==============================] - 0s 9ms/step - loss: 1.1605 - accuracy: 0.0000e+00 - mae: 0.7705
Epoch 344/500
13/13 [==============================] - 0s 9ms/step - loss: 1.0432 - accuracy: 0.0000e+00 - mae: 0.7378
Epoch 345/500
13/13 [==============================] - 0s 9ms/step - loss: 0.9797 - accuracy: 0.0000e+00 - mae: 0.6999
Epoch 346/500
13/13 [==============================] - 0s 8ms/step - loss: 1.1962 - accuracy: 0.0000e+00 - mae: 0.8235
Epoch 347/500
13/13 [==============================] - 0s 8ms/step - loss: 1.0622 - accuracy: 0.0000e+00 - mae: 0.7199
Epoch 348/500
13/13 [==============================] - 0s 8ms/step - loss: 1.0663 - accuracy: 0.0000e+00 - mae: 0.7359
Epoch 349/500
13/13 [==============================] - 0s 8m

13/13 [==============================] - 0s 9ms/step - loss: 0.7395 - accuracy: 0.0000e+00 - mae: 0.6045
Epoch 410/500
13/13 [==============================] - 0s 10ms/step - loss: 0.7774 - accuracy: 0.0000e+00 - mae: 0.6275
Epoch 411/500
13/13 [==============================] - 0s 9ms/step - loss: 0.7816 - accuracy: 0.0000e+00 - mae: 0.6240
Epoch 412/500
13/13 [==============================] - 0s 8ms/step - loss: 0.7921 - accuracy: 0.0000e+00 - mae: 0.6355
Epoch 413/500
13/13 [==============================] - 0s 10ms/step - loss: 0.7792 - accuracy: 0.0000e+00 - mae: 0.6211
Epoch 414/500
13/13 [==============================] - 0s 9ms/step - loss: 0.7958 - accuracy: 0.0000e+00 - mae: 0.6385
Epoch 415/500
13/13 [==============================] - 0s 9ms/step - loss: 0.8330 - accuracy: 0.0000e+00 - mae: 0.6649
Epoch 416/500
13/13 [==============================] - 0s 9ms/step - loss: 0.8687 - accuracy: 0.0000e+00 - mae: 0.6932
Epoch 417/500
13/13 [==============================] - 0s 10

In [34]:
model.evaluate(test_features, test_label)

4/4 [==============================] - 0s 9ms/step - loss: 11.7004 - accuracy: 0.0000e+00 - mae: 2.3725


[11.700369834899902, 0.0, 2.3725149631500244]

The accuracy of the model is quiet low. On evaluation, we can see that the loss is even higher, indicating model overfitting over the training dataset. We have different methods to try reduce the overfitting and reducing the loss, which we will see later on. Let's try to predict few results -

In [35]:
model.predict(test_features[:2])

1/1 [==============================] - 0s 55ms/step


array([[ 8.295283],
       [18.35007 ]], dtype=float32)

In [36]:
test_label[:2]

array([ 7.2, 18.8])

As you can see, the prediction is quiet deviated from the actual results, which means the model is unable to identify a proper relationship between the features and the labels. Try changing the number of neurons and layers to see the effect in the output.

<h3>So what you did here? </h3><br/>
<ol>
    <li> Used the Boston Housing dataset </li>
    <li> Looked into the basic data details </li>
    <li> Standardized the data using Scikit learn standard scaler </li>
    <li> Utilized GPU for training </li>
    <li> Created the model architecture with - <ol>
        <li>Input layer for the incoming data</li>
        <li>a Flatten layer</li>
        <li>3 dense neural network layers with 256, 128 and 1 neurons alongwith activation functions. </li></ol></li>
    <li> Compiled the model with loss and optimizer </li>
    <li> Used a callback function in the fit and fitted the model with training data </li>
    <li> Evaluated the model with test data </li>
    <li> Predicted on the trained model </li>
    </ol>